package com.xoff.ia.chess;

public enum MoveType {
    NA, PROMOTION_QUEEN, PROMOTION_BISHOP, PROMOTION_KNIGHT, PROMOTION_ROOK, PROMOTION_QUEEN_TAKE, PROMOTION_BISHOP_TAKE, PROMOTION_KNIGHT_TAKE, PROMOTION_ROOK_TAKE, LONG_CASTLE, SHORT_CASTLE, EP, TAKE;
}
